#!/usr/bin/env python3
"""Regenerate the shipped LTX-2.5 example workflows.

The examples are compiler output, never hand-edited. That is the point: if they
had to be maintained by hand they would drift from what the Director actually
builds, which is exactly what happened to the Director 2.x examples — they are
still LTX-2.3-shaped.

Run after changing the compiler, and commit the diff::

    python tools/build_examples.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from director.compiler import compile_spec  # noqa: E402
from director.core.spec import (  # noqa: E402
    DEFAULT_SIGMAS_STAGE1,
    DEFAULT_SIGMAS_STAGE2,
    AudioClip,
    LoraRef,
    MediaEntry,
    Reference,
    Segment,
    Spec,
)

OUTPUT = REPO_ROOT / "example_workflows" / "director_next"

#: The LTX-2.5 file names from the Hugging Face repository. A user who has run
#: the examples' Download All will have exactly these.
MODELS = {
    "unet": "ltx-2.5-22b-distilled-transformer-bf16.safetensors",
    "clip": "gemma4-12b-with-proj-ltx-2.5-bf16.safetensors",
    "vae": "ltx-2.5-video-vae-bf16.safetensors",
    "audio_vae": "ltx-2.5-audio-vae-bf16.safetensors",
    "upscaler": "ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors",
    "enhancer_clip": "gemma4_e2b_it_bf16.safetensors",
}


def base(name: str, mode: str) -> Spec:
    spec = Spec()
    spec.meta.name = name
    spec.meta.note = "Generated by tools/build_examples.py — do not edit by hand."
    spec.project.mode = mode  # type: ignore[assignment]
    spec.project.fps = 24.0
    spec.project.width, spec.project.height = 1280, 704
    spec.project.frames = 121
    spec.prompt.negative = "blurry, out of focus, low contrast, washed out, flickering"
    spec.generation.seed = 42
    spec.generation.sigmas_stage1 = list(DEFAULT_SIGMAS_STAGE1)
    spec.generation.sigmas_stage2 = list(DEFAULT_SIGMAS_STAGE2)
    spec.generation.save_prefix = f"video/LTXDirector_{mode}"
    spec.models.family = "ltx2.5"
    for key in ("unet", "clip", "vae", "audio_vae"):
        setattr(spec.models, key, MODELS[key])
    return spec


def image(spec: Spec, filename: str) -> str:
    entry = MediaEntry(filename=filename, kind="image", width=1280, height=704)
    spec.media[entry.id] = entry
    return entry.id


def keyframe(spec: Spec, filename: str, anchor: str, frame: int = 0) -> None:
    reference = Reference(role="keyframe", media=image(spec, filename), anchor=anchor)  # type: ignore[arg-type]
    reference.at.frame = frame
    reference.label = filename
    spec.references.append(reference)


def examples() -> dict[str, Spec]:
    out: dict[str, Spec] = {}

    t2v = base("Text to video", "t2v")
    t2v.prompt.raw = (
        "A lighthouse beam sweeps across a storm-lit harbour, rain streaking through the "
        "light as waves break over the sea wall. The camera holds still on a locked-off "
        "frame. Wind and surf fill the soundscape."
    )
    out["LTX-2.5_Director_T2V"] = t2v

    two_stage = base("Text to video, refined", "t2v")
    two_stage.prompt.raw = t2v.prompt.raw
    two_stage.generation.stages = 2
    two_stage.models.upscaler = MODELS["upscaler"]
    out["LTX-2.5_Director_T2V_Two_Stage"] = two_stage

    i2v = base("Image to video", "i2v")
    i2v.prompt.raw = (
        "Use the provided start image as the first frame. The subject turns slowly toward "
        "the window as the camera pushes in, tightening on their face."
    )
    keyframe(i2v, "first_frame.png", "start")
    out["LTX-2.5_Director_I2V"] = i2v

    fflf = base("First and last frame", "fflf")
    fflf.prompt.raw = (
        "The scene transforms smoothly from the opening frame to the closing one, holding "
        "the same lighting and lens throughout."
    )
    keyframe(fflf, "first_frame.png", "start")
    keyframe(fflf, "last_frame.png", "end")
    out["LTX-2.5_Director_FFLF"] = fflf

    keys = base("Keyframes", "keyframes")
    keys.prompt.raw = "A continuous move that passes through each pinned frame in turn."
    keyframe(keys, "first_frame.png", "start")
    keyframe(keys, "middle_frame.png", "index", 48)
    keyframe(keys, "last_frame.png", "end")
    out["LTX-2.5_Director_Keyframes"] = keys

    relay = base("Prompt Relay", "t2v")
    relay.prompt.raw = "A storm-lit harbour at night, shot on 35mm."
    relay.segments = [
        Segment(start=0, length=40, text="the lighthouse beam sweeps left across the water"),
        Segment(start=40, length=40, text="rain intensifies and the sea wall takes a wave"),
        Segment(start=80, length=41, text="the beam returns and the harbour goes quiet"),
    ]
    out["LTX-2.5_Director_Prompt_Relay"] = relay

    a2v = base("Audio to video", "a2v")
    a2v.prompt.raw = "A performance filmed in one take, cut to the supplied recording."
    a2v.audio.mode = "import"
    entry = MediaEntry(filename="soundtrack.wav", kind="audio", duration=12.0)
    a2v.media[entry.id] = entry
    a2v.audio.clips.append(AudioClip(media=entry.id, start=0, length=121))
    out["LTX-2.5_Director_A2V"] = a2v

    t2a = base("Text to audio", "t2a")
    t2a.prompt.raw = "Rain on a tin roof, distant thunder rolling in, no music."
    t2a.generation.save_prefix = "audio/LTXDirector_t2a"
    out["LTX-2.5_Director_T2A"] = t2a

    iclora = base("IC-LoRA motion control", "iclora")
    iclora.prompt.raw = "The same movement, restaged with a different subject and setting."
    clip = MediaEntry(filename="motion_source.mp4", kind="video",
                      width=1280, height=704, duration=5.0, fps=24.0)
    iclora.media[clip.id] = clip
    iclora.references.append(Reference(
        role="motion", media=clip.id, anchor="start", label="motion_source.mp4",
    ))
    iclora.models.loras.append(LoraRef(
        name="ltx-2.3-22b-ic-lora-motion-track-control-ref0.5.safetensors", kind="iclora",
    ))
    out["LTX-2.5_Director_ICLoRA"] = iclora

    return out


def main() -> int:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    written = []
    failed = []

    for name, spec in examples().items():
        result = compile_spec(spec.normalise(), layout="flat")
        if not result.ok:
            failed.append((name, [str(d) for d in result.report.errors]))
            continue
        path = OUTPUT / f"{name}.json"
        path.write_text(
            json.dumps(result.workflow, indent=1, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        written.append((name, len(result.workflow["nodes"])))

    for name, nodes in written:
        print(f"{name:44s} {nodes:3d} nodes")
    for name, errors in failed:
        print(f"{name:44s} FAILED: {errors}")

    _write_index(written)
    return 1 if failed else 0


def _write_index(written: list[tuple[str, int]]) -> None:
    lines = [
        "# Director Next example workflows",
        "",
        "These are **compiler output**, not hand-built graphs. Each one is what the",
        "LTX Director produces for a particular kind of shot, with the Director node",
        "itself removed — open one to see exactly what the editor's Generate button",
        "runs.",
        "",
        "Regenerate with `python tools/build_examples.py` after changing the compiler.",
        "",
        "Every graph expects the LTX-2.5 model set:",
        "",
    ]
    for key, filename in MODELS.items():
        folder = {
            "unet": "diffusion_models", "clip": "text_encoders", "vae": "vae",
            "audio_vae": "vae", "upscaler": "latent_upscale_models",
            "enhancer_clip": "text_encoders",
        }[key]
        lines.append(f"* `{filename}` → `ComfyUI/models/{folder}/`")
    lines += [
        "",
        "| Workflow | Nodes | What it does |",
        "| --- | --- | --- |",
    ]
    descriptions = {
        "LTX-2.5_Director_T2V": "Text to video with synchronised audio. Start here.",
        "LTX-2.5_Director_T2V_Two_Stage":
            "Generates at half size, upscales the latent, then refines. Slower, sharper.",
        "LTX-2.5_Director_I2V": "Opens on a still and moves from there.",
        "LTX-2.5_Director_FFLF": "Pins the first and last frames and fills between them.",
        "LTX-2.5_Director_Keyframes": "Pins any number of frames along the timeline.",
        "LTX-2.5_Director_Prompt_Relay":
            "Three prompt regions over one shot, in a single sampling pass.",
        "LTX-2.5_Director_A2V":
            "Follows a supplied soundtrack, frozen through sampling and muxed back in.",
        "LTX-2.5_Director_T2A": "Audio only — no video VAE, no decode.",
        "LTX-2.5_Director_ICLoRA": "Follows a reference clip's motion through an IC-LoRA.",
    }
    for name, nodes in written:
        lines.append(f"| [`{name}.json`](./{name}.json) | {nodes} | "
                     f"{descriptions.get(name, '')} |")
    lines += [
        "",
        "Image and audio filenames in these graphs are placeholders "
        "(`first_frame.png`, `soundtrack.wav`). Point them at your own files, or build",
        "the shot in the Director node and press Generate instead.",
        "",
    ]
    (OUTPUT / "README.md").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    raise SystemExit(main())
